version: "3"

services:
  postgres:
    container_name: postgres_container
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - nisomnia_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  web:
    container_name: web_container
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - nisomnia_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

networks:
  nisomnia_network:
    driver: bridge

volumes:
  postgres:
