version: "3"

services:
  web:
    container_name: web_container
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: always
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.<unique-name>.rule=Host(`nisomnia.com`)"
      - "traefik.http.routers.<unique-name>.entrypoints=websecure"
      - "traefik.http.routers.<unique-name>.tls.certResolver=letsencrypt"
      - "traefik.http.services.<unique-name>.loadbalancer.server.port=3000"
networks:
  dokploy-network:
    external: true
