export const {
  APP_ENV: appEnv,
  PORT: port,
  DATABASE_URL: databaseUrl,
  GOOGLE_CLIENT_ID: googleClientId,
  GOOGLE_CLIENT_SECRET: googleClientSecret,
  GOOGLE_REDIRECT_URL: googleRedirectUrl,
  PUBLIC_SITE_DOMAIN: publicSiteDomain,
  PUBLIC_SITE_TITLE: publicSiteTitle,
  PUBLIC_SITE_DESCRIPTION: publicSiteDescription,
  PUBLIC_ROBOTS: publicRobots,
  PUBLIC_FACEBOOK_USERNAME: publicFacebookUsername,
  PUBLIC_X_USERNAME: publicXUsername,
  PUBLIC_INSTAGRAM_USERNAME: publicInstagramUsername,
  PUBLIC_TIKTOK_USERNAME: publicTiktokUsername,
  PUBLIC_WHATSAPP_CHANNEL_USERNAME: publicWhatsappChannelUsername,
  PUBLIC_YOUTUBE_USERNAME: publicYoutubeUsername,
  PUBLIC_ADSENSE_CLIENT_ID: publicAdsenseClientId,
  PUBLIC_GA_ID: publicGaId,
  PUBLIC_SUPPORT_EMAIL: publicSupportEmail,
  PUBLIC_WHATSAPP_NUMBER: publicWhatsappNumber,
  PUBLIC_ADDRESS: publicAddress,
  PUBLIC_LOGO_OG_URL: publicLogoOgUrl,
  PUBLIC_LOGO_OG_WIDTH: publicLogoOgWidth,
  PUBLIC_LOGO_OG_HEIGHT: publicLogoOgHeight,
  CF_ACCOUNT_ID: cfAccountId,
  R2_BUCKET: r2Bucket,
  R2_REGION: r2Region,
  R2_ACCESS_KEY: r2AccessKey,
  R2_SECRET_KEY: r2SecretKey,
  R2_DOMAIN: r2Domain,
} = import.meta.env

export const publicSiteUrl = `https://${publicSiteDomain || "nisomnia.com"}`
export const publicApiUrl = `https://${publicSiteDomain || "nisomnia.com"}/api`
